# Generated by Django 2.2 on 2020-05-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Term',
            new_name='term',
        ),
    ]
