# Generated by Django 2.2 on 2020-05-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20200510_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cams',
            name='flag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
