# Generated by Django 2.2 on 2020-05-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_auto_20200514_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='hiring_status',
        ),
    ]
