# Generated by Django 2.2.13 on 2022-01-06 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_auto_20200526_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
