# Generated by Django 3.2.12 on 2022-04-28 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0013_auto_20220428_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delete', to=settings.AUTH_USER_MODEL),
        ),
    ]
