# Generated by Django 3.2.12 on 2022-05-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_schedule_deleted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cams_update_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Dates',
                'verbose_name_plural': 'Dates',
            },
        ),
    ]
