# Generated by Django 3.2.14 on 2023-04-03 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
