# Generated by Django 4.0.3 on 2022-03-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_alter_course_subject'),
        ('main', '0003_auto_20200618_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
